version: '3.1'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: rmics-mysql
    environment:
      MYSQL_DATABASE: rmics_db_v2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.mysqldata:/var/lib/mysql
      # - ./docker/mysql/log:/var/log/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    # Fix mbind error
    # This is could be a initial fix for now, this might disable the mysql security features
    # https://thegeekbin.com/mbind-operation-not-permitted-docker-mysql/
    security_opt:
      - seccomp:unconfined
